name: Test environment values flow with a push
on:
  push:

jobs:
  test-dev:
    uses: lsipii/test/.github/workflows/test.yml@main
    secrets: inherit
    with:
      environment: dev
  test-staging:
    uses: lsipii/test/.github/workflows/test.yml@main
    secrets: inherit
    with:
      environment: staging
