name: Test environment values flow on github actions
on:
  workflow_dispatch:
    inputs:
      stage_environment:
        description: Environment where to deploy the stack (dev, staging)
        type: environment
        required: true
  workflow_call:
    inputs:
      stage_environment:
        description: Environment where to deploy the stack (dev, staging)
        type: string
        required: true
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    environment: ${{ inputs.stage_environment }}
    steps:
      - name: Environment test
        run: |
          echo ${BAZ} | sed 's/./& /g'
        env:
          BAZ: ${{ secrets.BAZ }}
