name: Test environment values flow on github actions
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment where to deploy the stack (dev, staging)
        type: environment
        required: true
        options:
          - staging
          - dev

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: Environment test
        run: ./test.sh
        env:
          BAZ: ${{ secrets.BAZ }}
